<%@ Page Title="Kezdőlap" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"
    CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <h2>
        Üdv az oldalon!
    </h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eleifend varius purus ut varius. Vestibulum eget aliquam justo. Nullam aliquet elit eu augue vulputate sed tincidunt mi mollis. Sed vehicula, augue eget iaculis semper, odio orci imperdiet mi, quis faucibus nisi ipsum sit amet nulla. Quisque vel tortor non erat aliquet rhoncus ut a libero. Aenean lobortis dignissim felis, eget posuere odio vestibulum eget. Curabitur tempus massa quis ante cursus dictum. Pellentesque scelerisque mattis molestie. Cras eget turpis justo, nec ornare enim. Quisque tellus ante, molestie sit amet consequat non, tincidunt ut dui. Morbi eleifend, quam non commodo posuere, neque risus dignissim enim, quis venenatis leo augue ac neque. Nunc pulvinar eros at mauris placerat quis convallis enim tempus. Phasellus sit amet leo in felis ultrices suscipit. Nam a urna sed mi ullamcorper consectetur. Maecenas ut justo a risus fermentum bibendum. Quisque massa mi, ornare in placerat interdum, pharetra vel sapien. Mauris vel sagittis sapien. Vestibulum ac est et odio imperdiet ultricies eu ac est. Fusce sed aliquet nisi.</p>
    <p>Quisque vitae ipsum vel magna elementum bibendum sit amet sit amet lectus. Suspendisse vitae justo tortor. Mauris vulputate, lectus facilisis feugiat volutpat, ipsum erat sollicitudin sem, sed pharetra arcu libero quis urna. Duis leo eros, porttitor non bibendum ut, sollicitudin et velit. Morbi arcu ligula, gravida sit amet blandit vitae, lobortis sed dui. Aenean imperdiet dapibus elit vitae rhoncus. Maecenas aliquet elit quis sapien interdum vel rhoncus quam ullamcorper. Vivamus auctor, risus sed interdum luctus, elit felis ornare arcu, id rhoncus lacus nisl id massa. Aenean tincidunt quam elit, sed egestas lorem. Curabitur a turpis eget nibh tempus aliquam. Vivamus quis nibh nec augue vestibulum varius. Maecenas nunc felis, suscipit in pretium eget, lacinia consectetur metus.</p>
    <p>In egestas dignissim viverra. Nam ullamcorper nibh eget libero vulputate rhoncus. Suspendisse malesuada, dui sit amet ornare facilisis, metus est ornare nibh, non facilisis nunc leo nec diam. Ut ac neque felis, a interdum ipsum. Donec viverra, odio volutpat porta faucibus, mi ipsum semper ante, sagittis viverra purus lorem non tellus. Mauris accumsan, massa non vehicula tincidunt, justo purus pellentesque est, non tempus tellus tellus et erat. Nulla eu diam eros. Pellentesque sed tortor nec erat auctor laoreet quis sed augue. Sed luctus, odio non semper sagittis, nunc neque suscipit quam, et aliquet urna leo et enim. Nulla bibendum turpis eu urna accumsan ac placerat erat suscipit. Curabitur cursus, nunc ac fermentum egestas, nibh ipsum pulvinar tellus, vel feugiat leo quam ac ante. Vestibulum est enim, commodo a egestas eget, mattis in odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sed ligula tellus, sit amet commodo lorem. Integer nec magna sit amet dui pharetra imperdiet. Mauris dapibus dui pellentesque augue porttitor in interdum erat aliquam. Suspendisse vel venenatis risus.</p>
</asp:Content>
